### ISSUE TITLE
Plans - Comprehensive List of future features/changes

### ISSUE THREAD

**Issue by d0p3t** [d0p3t/fivem-js#11]
This issue is meant to be used as a way to keep track of upcoming features and suggestions by you. If you'd like to leave a suggestion, please do so below.

Below is a list of features that are currently in the pipeline or are already added. I'll expand on this issue once time goes by.

* Timerbars class ✅ 
* Combine Loading Prompt + Timerbars ✅ 
* Color wheel for Menu UI
* Labels class (for localized text support)
* Support non 1080p displays for Menu UI creation ✅
* Add Pickups - Either own class or in `World`
* IPL and Interiors loader/manager
* Toggle PvP ✅

**Comment by ghost** [comment]
Looking forward to progress on the project. Have been developing with it for a couple of weeks now, and really enjoying it.
