### ISSUE TITLE
ESX Integration

### ISSUE THREAD

**Issue by GiroudMathias** [d0p3t/fivem-js#29]
Hello,
I created a library for ESX to complement your module!
It might be useful to reference it here!

Great work!

https://github.com/GiroudMathias/fivem-esx-js

**Comment by d0p3t** [comment]
Thank you, but fivem-js has nothing to do with a framework and won't be promoting that too. 

fivem-js wraps only GTA natives into use able classes/objects.

Good to see others create wrappers for other aspects of FiveM 👍
