### ISSUE TITLE
Package module UUIDV4 has wrong letter case and fail to import in Linux

### ISSUE THREAD

**Issue by VPagani** [d0p3t/fivem-js#30]
Linux is case-sensitive for files and directories so the compiled file `uuidv4.js` is not recognized as `UUIDV4.js` and throws an error message `Cannot find module './UUIDV4'`.

Maybe it is caused by compiling and uploading the package from a Windows computer which is case-insensitive.

You can check here the wrong uploaded files (`uuidv4.js` and `uuidv4.d.ts`):
https://unpkg.com/browse/fivem-js@1.3.0/lib/utils/

**Comment by d0p3t** [comment]
Fixed in 1.3.1
