### ISSUE TITLE
Discord Link Broken

### ISSUE THREAD

**Issue by dezmathio** [d0p3t/fivem-js#33]
I've tried from multiple different IPs/machines now, but 
when I go to https://discord.d0p3t.nl/
it always returns:

```
This site can’t be reached
discord.d0p3t.nl’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

Not entirely sure how useful that discord is specifically but I just figured I would let you know it's not working.

**Comment by d0p3t** [comment]
This happened due to DNS changes on CloudFlare that I made last night. 

Should be fixed now!

**Comment by dezmathio** [comment]
yup that worked thanks
