### ISSUE TITLE
Cannot read property 'exists' of null

### ISSUE THREAD

**Issue by jokeruarwentto** [d0p3t/fivem-js#34]
**How to reproduce**
var peds = Cfx.World.getAllPeds();
log(peds);

**Logs**
[   3774094] [    GTAProcess]             MainThrd/ ^1SCRIPT ERROR in ticker: TypeError: Cannot read property 'exists' of null^7
[   3774110] [    GTAProcess]             MainThrd/ 
[   3774125] [    GTAProcess]             MainThrd/ ^3> Function.getAllPeds^7 (^5@test/dist/client/index.js^7:5676)
[   3774141] [    GTAProcess]             MainThrd/ ^3> ^7 (^5@test/dist/client/index.js^7:8567)
[   3774156] [    GTAProcess]             MainThrd/ ^3> ^7 (^5@test/dist/client/index.js^7:8539)
[   3774156] [    GTAProcess]             MainThrd/ ^3> __awaiter^7 (^5@test/dist/client/index.js^7:8518)
[   3774172] [    GTAProcess]             MainThrd/ ^3> callback^7 (^5@test/dist/client/index.js^7:8566)
[   3774172] [    GTAProcess]             MainThrd/

**Comment by d0p3t** [comment]
Potential fix as referenced in latest commit. Please checkout development again and try :)

**Comment by d0p3t** [comment]
Should be fixed in https://github.com/d0p3t/fivem-js/commit/b937f238b3843cf4774104b1f9f3fd14fedc5ffa

Pushed to 1.3.3
