### ISSUE TITLE
[BUG] TimerBar - Progress not display

### ISSUE THREAD

**Issue by grdlo** [d0p3t/fivem-js#42]
**Describe the bug**
The Progress of TimerBar are not showed

**To Reproduce**
The used code is :
```JavaScript
const bar = new Cfx.Timerbar("Soif 💧", true)
bar.Progress(0.5)
bar.Visible(true)
```
(i'm currently using the latest version of fivem-js)

**Screenshots**
![screenshot](https://i.ibb.co/68CXqG5/Capture.png)

**FiveM Client (please complete the following information):**
 - Canary: [ no ]
 - Version [ unknow ]

**FiveM Server:**
 - OneSync: **Infinity** (with all parameters active)
- Artifact: [ 3184 ]

**Comment by d0p3t** [comment]
This may be a bug due to changes on how the timer bars are displayed. I will look into it, thanks

**Comment by d0p3t** [comment]
I could not reproduce the bug. There seems to be an issue with your code as well. `bar.Progress` and `bar.Visible` are properties, not functions. By default a timerbar is visible, so there's also not a reason to set it to true.

https://i.imgur.com/sN81QaU.png

```ts
const bar = new Cfx.Timerbar('Soif 💧', true);
bar.Progress = 0.5;
bar.Visible = true;
```

See https://d0p3t.nl/classes/timerbar.html#progress
