### ISSUE TITLE
[Question]Should use master branch for development?

### ISSUE THREAD

**Issue by imckl** [d0p3t/fivem-js#54]
I'm about to test my [PR](https://github.com/d0p3t/fivem-js/pull/53) to fix any issue in-game. However it throws error which is not the change I've made.

(I've done nothing on /lib/ui/menu/items/UIMenuItem)
![image](https://user-images.githubusercontent.com/20377660/110196315-a5f1d300-7e7e-11eb-8c7f-b5c5ff11a73b.png)

This alter the actual test I wanna do, and might be overhead to temporary remove those changes.

So should we create PR-branch based on functional branch(eg. master branch) for development, instead of the development branch?

**Comment by mythicalbro** [comment]
There have been some changes indeed, but I am always using dev branch and have not had any problems yet with the menu or any other stuff I use. If there is issue then you should try to find out what exactly causes that issue. You should do pull requests to dev branch not master branch.

**Comment by imckl** [comment]
Thanks, I'll figure that out
