### ISSUE TITLE
Documentation website down

### ISSUE THREAD

**Issue by FusionPwN** [d0p3t/fivem-js#67]
Hey bro, your website is down, no access to the documentation

**Comment by AvarianKnight** [comment]
d0p3t is currently away and it's possible that he won't be back for a while.

Here's a temporary backup until he is well and able to put everything back up

https://fivemjs.avarian.dev/

Alternatively, you can also yourself by forking the project, and do `npm run doc`

**Comment by FusionPwN** [comment]
> 
> 
> d0p3t is currently away and it's possible that he won't be back for a while.
> 
> Here's a temporary backup until he is well and able to put everything back up
> 
> https://fivemjs.avarian.dev/
> 
> Alternatively, you can also yourself by forking the project, and do `npm run doc`

Thank you @AvarianKnight, yeah I read somewhere that d0p3t was ill, hope he gets well soon :D
